general {
    hide_cursor = true
    grace = 2
    disable_loading_bar = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 4
    brightness = 0.5
}

input-field {
    monitor =
    size = 300, 55
    position = 0, -80
    halign = center
    valign = center

    outer_color = rgb(80, 80, 80)
    inner_color = rgb(15, 15, 15)
    font_color = rgb(230, 230, 230)

    outline_thickness = 2
    rounding = 8

    placeholder_text = <span foreground="##888888">Password...</span>
    fail_text = <span foreground="##ff5555">Authentication failed</span>

    fade_on_empty = false
}

label {
    monitor =
    text = $TIME
    color = rgb(230, 230, 230)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgb(150, 150, 150)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 25
    halign = center
    valign = center
}
image {
    monitor =
    path = /home/skywie/Pictures/yuta.jpg
    size = 150
    border_size = 3
    border_color = rgb(180, 180, 180)
    rounding = -1

    position = 0, 250
    halign = center
    valign = center
}
